runtime: python37
env: standard

entrypoint: gunicorn -b :$PORT main:app

default_expiration: "1m"

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto